site_name: Quantifyr
site_description: A hybrid classical-quantum molecular machine learning platform
site_url: https://Pruneye.github.io/Quantifyr/
repo_url: https://github.com/Pruneye/Quantifyr
repo_name: Pruneye/Quantifyr

nav:
  - Home: index.md
  - Tutorials:
    - Data Processing: tutorials/data_processing.md
    - Visualization: tutorials/visualization.md
    - API Reference: tutorials/api-reference.md

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3

extra:
  version: "1.0.0"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Pruneye/Quantifyr

extra_css:
  - stylesheets/extra.css?v=1.0.1

extra_javascript:
  - javascripts/sidebar-sync.js 